<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="register.aspx.cs" Inherits="student_msc_stored.register" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <asp:Label ID="Label1" runat="server" Text="name:"></asp:Label>
        <asp:TextBox ID="txt_name" runat="server"></asp:TextBox>
        <div>
            <asp:Label ID="Label2" runat="server" Text="Email:"></asp:Label>
            <asp:TextBox ID="txt_age" runat="server"></asp:TextBox>
            <br />
            <asp:Label ID="Label6" runat="server" Text="Password:"></asp:Label>
            <asp:TextBox ID="txt_pass" runat="server" OnTextChanged="txt_age0_TextChanged"></asp:TextBox>
            <br />
            <asp:Label ID="Label3" runat="server" Text="Gender:"></asp:Label>
&nbsp;<asp:RadioButtonList ID="rbtn_g" runat="server">
    <asp:ListItem>Male</asp:ListItem>
    <asp:ListItem>Female</asp:ListItem>
            </asp:RadioButtonList>
            <br />
            <asp:Label ID="Label4" runat="server" Text="Subject:"></asp:Label>
            <asp:CheckBoxList ID="ch_btn" runat="server">
                <asp:ListItem>Asp.net</asp:ListItem>
                <asp:ListItem>C#</asp:ListItem>     
            </asp:CheckBoxList>
            <br />
            <asp:Label ID="Label5" runat="server" Text="Course:"></asp:Label>
            <asp:DropDownList ID="ddl_course" runat="server" AutoPostBack="true">
                <asp:ListItem>MscIT</asp:ListItem>
                <asp:ListItem>Bca</asp:ListItem>
                <asp:ListItem>BscIT</asp:ListItem>
            </asp:DropDownList>
            <br />
            <br />
            <asp:Button ID="Button1" runat="server" Text="Submit" OnClick="Button1_Click"  />
            <br />
            <br />
            <asp:GridView ID="gv_stud" runat="server" DataKeyNames="Id" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnRowCancelingEdit="gv_stud_RowCancelingEdit" OnRowDeleting="gv_stud_RowDeleting" OnRowEditing="gv_stud_RowEditing" OnRowUpdating="gv_stud_RowUpdating"></asp:GridView>
        </div>
    </form>
</body>
</html>
